all: main.cpp src/get_PaiXin.cc src/contructor_PaiXin.cc src/operator_PaiXin.cc src/tree.cc src/other_funcion_PaiXin.cc
	g++ -std=c++11 -I./include main.cpp src/get_PaiXin.cc src/contructor_PaiXin.cc src/operator_PaiXin.cc src/other_funcion_PaiXin.cc src/tree.cc -o bin/canju -g             
run: all
	./bin/canju
clean :
	rm bin/canju
